# launching ec2 instance
- name: provision of ec2 instance
  ec2:
    key_name: "{{ KEY_NAME }}"
    region: "{{ REGION }}"
    instance_type: "{{ INSTANCE_TYPE }}"
    image: "{{ AMI_ID }}"
    wait: yes
    count: " {{ COUNT }} "
    instance_tags:
      Name: "{{ INSTANCE_NAME }}"
    monitoring: no
    vpc_subnet_id: "{{ VPC_SUBNET_ID }}"
    assign_public_ip: "{{ ASSIGN_PUBLIC_IP }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ VOLUME_SIZE_GB }}"
        delete_on_termination: true
    group: "{{ SECURITY_GROUP }}"
  register: ec2_out
- name: wait for SSH to comeup
  wait_for:
    host:{{ item.public_ip }}
    port:22
    delay:60
    timeout:320
    state:started
  with_items: '{{ec2_out.instances}}'
